# Generated by Django 3.1.1 on 2020-09-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete_stat',
        ),
        migrations.DeleteModel(
            name='Complete_stat',
        ),
    ]
